---
build_from:
  aarch64: arm64v8/bookworm-20230208-slim
  amd64: amd64/bookworm-20230208-slim
  armhf: arm32v5/bookworm-20230208-slim
  armv7: arm32v7/bookworm-20230208-slim
  i386: i386/bookworm-20230208-slim
#codenotary:
#  signer: codenotary@frenck.dev
